import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import CreateProductModal from '@/components/modals/CreateProductModal';
import CartModal from '@/components/modals/CartModal';
import ToastProvider from './providers/ToastProvider';
import Footer from '@/components/Footer';
import { Benne } from 'next/font/google';
import { Rubik } from 'next/font/google';
import { Roboto } from 'next/font/google';
import { Rakkas } from 'next/font/google';
import { DM_Sans } from 'next/font/google';
import { Caveat } from 'next/font/google';
import AuthProvider from '@/components/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

const benne = Benne({
  subsets: ['latin'],
  variable: '--font-benne',
  weight: '400',
});

const rubik = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
  weight: '400',
});

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: '400',
});

const rakkas = Rakkas({
  subsets: ['latin'],
  variable: '--font-rakkas',
  weight: '400',
});

const dmSans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dmsans',
  weight: '900',
});

const caveat = Caveat({
  subsets: ['latin'],
  variable: '--font-caveat',
  weight: '600',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${benne.variable} ${rubik.variable} ${roboto.variable} ${rakkas.variable} ${dmSans.variable} ${caveat.variable} min-w-[250px]`}
      >
        {' '}
        <AuthProvider>
          <ToastProvider />

          <CreateProductModal />
          <CartModal />
          <Navbar />

          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
