import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import CreateProductModal from '@/components/modals/CreateProductModal';
import CartModal from '@/components/modals/CartModal';
import ToastProvider from './providers/ToastProvider';
import Footer from '@/components/Footer';
import { Benne } from 'next/font/google';
import { Rubik } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

const benne = Benne({
  subsets: ['latin'],
  variable: '--font-benne',
  weight: '400',
});

const rubik = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${benne.variable} ${rubik.variable}`}>
        <ToastProvider />
        <CreateProductModal />
        <CartModal />
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
